# Generated by Django 4.1.6 on 2023-03-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preinscripcion_legislacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.IntegerField()),
                ('acepta_terminos_y_condiciones', models.BooleanField(default=False)),
                ('suscripcion', models.BooleanField(default=True)),
                ('date_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
