# Generated by Django 4.1.6 on 2023-03-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinscripcion_legislacion',
            name='acepta_terminos_y_condiciones',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='preinscripcion_legislacion',
            name='whatsapp',
            field=models.BigIntegerField(),
        ),
    ]
